-- Create the TrainerPortal database
DROP DATABASE IF EXISTS trainer_portal;
CREATE DATABASE trainer_portal;
\c trainer_portal

BEGIN TRANSACTION;

CREATE TABLE app_user
(
    -- account
    user_id    int          GENERATED BY DEFAULT AS IDENTITY,
    username   varchar(25)  NOT NULL UNIQUE,
    role       varchar(10)  NOT NULL,

    -- authentication
    password   varchar(256) NOT NULL,
    salt       varchar(256) NOT NULL,

    -- personal information
    first_name varchar(25)  NOT NULL,
    last_name  varchar(25)  NOT NULL,
    address    varchar(120),
    city       varchar(30),
    state      varchar(2),
    zip        varchar(16),
        
    constraint pk_app_user primary key (user_id),
    constraint chk_role CHECK (role IN ('Trainer', 'Client'))
);

CREATE TABLE client
(
    user_id int NOT NULL UNIQUE,

    constraint pk_client primary key (user_id)
);

CREATE TABLE trainer
(
    user_id               int     NOT NULL UNIQUE,
    is_public             boolean NOT NULL DEFAULT false,
    hourly_rate           int,
    rating                int,
    philosophy            varchar(80),
    biography             text,
    certifications_pickle varchar,

    constraint pk_trainer primary key (user_id),
    constraint chk_role CHECK (rating BETWEEN 0 AND 5)
);

CREATE TABLE client_list 
(
    trainer_id    int NOT NULL,
    client_id     int NOT NULL,
    private_notes text[],

    constraint pk_client_list primary key (trainer_id, client_id)
);

CREATE TABLE message
(
    message_id   int       GENERATED BY DEFAULT AS IDENTITY,
    sender_id    int       NOT NULL,
    recipient_id int       NOT NULL,
    post_date    timestamp NOT NULL DEFAULT NOW(),
    unread       boolean   NOT NULL DEFAULT true,
    subject      varchar(250),
    message      text,

    constraint pk_private_message primary key (message_id)
);

CREATE TABLE workout_plan
(
    workoutplan_id      int GENERATED BY DEFAULT AS IDENTITY,
    trainer_id          int NOT NULL,
    client_id           int NOT NULL,
    days_of_week        varchar(7)   NOT NULL DEFAULT 'FFFFFFF',
    title               varchar(30),
    body                varchar(250),

    constraint pk_workout_plan primary key (workoutplan_id, trainer_id, client_id)
);

-- Stored Procedures
CREATE OR REPLACE FUNCTION random_integer(low INT ,high INT)
RETURNS INT AS
$$
BEGIN
    RETURN floor(random()* (high-low + 1) + low);
END;
$$
LANGUAGE 'plpgsql' STRICT;

CREATE OR REPLACE FUNCTION random_boolean()
RETURNS BOOLEAN AS
$$
BEGIN
    IF random() < 0.5 THEN
        RETURN false;
    ELSE
        RETURN true;
    END IF;
END;
$$
LANGUAGE 'plpgsql' STRICT;

-- user data
INSERT INTO app_user 
 (user_id , first_name , last_name   , username                 , password , salt   , role     , address                  , city                , state , zip) VALUES
 (1       , 'Test'     , 'Trainer'   , 'trainer'                , 'pass'   , 'salt' , 'Client' , '558 Cliffe Knoll'       , 'Koelpinberg'       , 'OH'  , '41042')
,(2       , 'Elise'    , 'Mayert'    , 'Lewis.Paucek'           , 'pass'   , 'salt' , 'Client' , '705 Fenton Ride'        , 'South Yvonne'      , 'MD'  , '41042')
,(3       , 'Zella'    , 'Hilpert'   , 'Arvel.Ruecker'          , 'pass'   , 'salt' , 'Client' , '626 Lunnfields Lane'    , 'Doramouth'         , 'OR'  , '41042')
,(4       , 'Darius'   , 'Thompson'  , 'Ebba.Mueller47'         , 'pass'   , 'salt' , 'Client' , '261 Crossley West'      , 'East Carlotta'     , 'IN'  , '41042')
,(5       , 'Cristina' , 'Russel'    , 'Bradford.Ziemann'       , 'pass'   , 'salt' , 'Client' , '658 Rosebank By-Pass'   , 'Orionburgh'        , 'DE'  , '41042')
,(6       , 'Test'     , 'Client'    , 'client'                 , 'pass'   , 'salt' , 'Client' , '648 Hanbury Green'      , 'Langoshmouth'      , 'ME'  , '41042')
,(7       , 'Ellsworth', 'Rutherford', 'Maximillian.Schamberger', 'pass'   , 'salt' , 'Client' , '557 Spa Road'           , 'East Janis'        , 'RI'  , '41042')
,(8       , 'Eloise'   , 'Skiles'    , 'Catherine.Moore'        , 'pass'   , 'salt' , 'Client' , '921 Johnson Moorings'   , 'Stoltenbergside'   , 'WY'  , '41042')
,(9       , 'Wilhelm'  , 'Effertz'   , 'Skyla_Rowe46'           , 'pass'   , 'salt' , 'Client' , '232 Shannon Glas'       , 'South Cassidyton'  , 'WY'  , '41042')
,(10      , 'Bridgette', 'Wisozk'    , 'Jerrod55'               , 'pass'   , 'salt' , 'Client' , '639 Old Oak Rise'       , 'Swaniawskifurt'    , 'PA'  , '41042')
,(11      , 'Lesley'   , 'Harris'    , 'Carter29'               , 'pass'   , 'salt' , 'Client' , '330 Knole Grove'        , 'New Braeden'       , 'AR'  , '41042')
,(12      , 'Dayna'    , 'Rohan'     , 'Sheila67'               , 'pass'   , 'salt' , 'Client' , '336 Ferndale Dell'      , 'North Foster'      , 'NJ'  , '41042')
,(13      , 'Morton'   , 'Schaefer'  , 'Obie_Rath'              , 'pass'   , 'salt' , 'Client' , '897 Hay Lea'            , 'North Naomiemouth' , 'WA'  , '41042')
,(14      , 'Amira'    , 'Sawayn'    , 'Jenifer.Bernier'        , 'pass'   , 'salt' , 'Client' , '487 Tudor Orchard'      , 'South Dusty'       , 'WA'  , '41042')
,(15      , 'Gino'     , 'Gutmann'   , 'Warren79'               , 'pass'   , 'salt' , 'Client' , '895 Barnes Crest'       , 'East Alysson'      , 'NH'  , '41042')
,(16      , 'Reilly'   , 'Mayer'     , 'Keegan_Maggio'          , 'pass'   , 'salt' , 'Client' , '365 Ger-Y-Ffrwd'        , 'South Sherman'     , 'CT'  , '41042')
,(17      , 'Sonny'    , 'Mohr'      , 'Bernadette_Gorczany'    , 'pass'   , 'salt' , 'Client' , '355 Rusland Park'       , 'Stantonberg'       , 'CT'  , '41042')
,(18      , 'Hayley'   , 'Anderson'  , 'Ellis_Brakus'           , 'pass'   , 'salt' , 'Client' , '671 Buckley Park'       , 'West Norval'       , 'KY'  , '41042')
,(19      , 'Hailee'   , 'Glover'    , 'Aida78'                 , 'pass'   , 'salt' , 'Client' , '136 Almond Elms'        , 'New Annetta'       , 'IN'  , '41042')
,(20      , 'Conner'   , 'Abshire'   , 'Lessie.McKenzie98'      , 'pass'   , 'salt' , 'Client' , '849 Sutton Parkway'     , 'McLaughlinbury'    , 'OR'  , '41042')
,(21      , 'Isaias'   , 'Medhurst'  , 'Brendon_Hegmann'        , 'pass'   , 'salt' , 'Client' , '486 Blenkarne Road'     , 'Kristopherberg'    , 'WA'  , '41042')
,(22      , 'Christine', 'Tillman'   , 'Unique_Davis'           , 'pass'   , 'salt' , 'Client' , '740 Jesmond Isaf'       , 'North Mekhi'       , 'NC'  , '41042')
,(23      , 'Dandre'   , 'Romaguera' , 'Monserrate.Yost81'      , 'pass'   , 'salt' , 'Client' , '539 Colliers Villas'    , 'Melbaport'         , 'CT'  , '41042')
,(24      , 'Gayle'    , 'Dare'      , 'Emerson_Labadie'        , 'pass'   , 'salt' , 'Client' , '913 Sandpiper Laurels'  , 'South Monroe'      , 'OK'  , '41042')
,(25      , 'Ezra'     , 'Zemlak'    , 'Irving.Pouros'          , 'pass'   , 'salt' , 'Client' , '260 Davis Farm'         , 'Guillermoton'      , 'AR'  , '41042')
,(26      , 'Maiya'    , 'Grady'     , 'Leonor.Sawayn38'        , 'pass'   , 'salt' , 'Client' , '862 Greenfinch Gardens' , 'Thompsonmouth'     , 'SD'  , '41042')
,(27      , 'Jonatan'  , 'Feeney'    , 'Maybelle_Lang92'        , 'pass'   , 'salt' , 'Client' , '692 Henry Side'         , 'South Genevieveton , 'DE'  , '41042')
,(28      , 'Jalon'    , 'Robel'     , 'Felicita1'              , 'pass'   , 'salt' , 'Client' , '530 Allan Celyn'        , 'West Kodymouth'    , 'AZ'  , '41042')
,(29      , 'Einar'    , 'Herzog'    , 'Rusty.Cormier18'        , 'pass'   , 'salt' , 'Client' , '291 Devonshire Street'  , 'South Karliport'   , 'VT'  , '41042')
,(30      , 'Casandra' , 'Reichel'   , 'Elisabeth.Auer'         , 'pass'   , 'salt' , 'Client' , '210 Austin Court'       , 'South Karliport'   , 'VT'  , '41042')
;

INSERT INTO trainer (user_id,hourly_rate,rating,is_public,philosophy,biography,certifications_pickle) VALUES
 (1,55,1,true,'We need to quantify the solid state SSL protocol!','Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry''s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.','["American Council on Exercise (ACE)", "National Academy of Sports Medicine (NASM)", "International Sports Sciences Association (ISSA)", "American College of Sports Medicine (ACSM)", "National Strength and Conditioning Association (NSCA)", "National Federation of Professional Trainers (NFPT)"]')
,(2,25,5,true,'You can''t back up the firewall without synthesizing the 1080p XSS interface!','Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry''s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', '["International Sports Sciences Association (ISSA)", "National Strength and Conditioning Association (NSCA)", "National Federation of Professional Trainers (NFPT)"]')
,(3,60,2,true,'I''ll calculate the bluetooth AGP transmitter, that should sensor the FTP driver!','Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry''s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', '["National Strength and Conditioning Association (NSCA)", "National Federation of Professional Trainers (NFPT)"]')
,(4,200,4,true,'Try to transmit the IB firewall, maybe it will transmit the primary transmitter!','Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry''s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', '["American Council on Exercise (ACE)", "American College of Sports Medicine (ACSM)", "National Strength and Conditioning Association (NSCA)", "National Federation of Professional Trainers (NFPT)"]')
,(5,25,2,true,'You can''t index the pixel without copying the optical ADP matrix!','Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry''s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', '["National Federation of Professional Trainers (NFPT)"]')
;


INSERT INTO message (message_id, sender_id, recipient_id, post_date, unread, subject, message) VALUES
 (1,1,2,'1/10/2019',true,'Subject 1', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.')
,(2,1,2,'1/10/2019',false,'Subject 2', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.')
,(3,1,2,'1/10/2019',true,'Subject 3', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.')
,(4,2,1,'1/11/2019',true,'Reply 1', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.')
,(5,2,1,'1/11/2019',false,'Reply 2', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.')
;

-- client list
INSERT INTO client_list (trainer_id, client_id) VALUES
 (1,6)
,(1,7)
;

-- work_out plan
INSERT INTO workout_plan (trainer_id, client_id, days_of_week, title, body) VALUES 
(1, 6, 'FTFTFTF', 'Legs', 'Do 5 sets of 10 squats and 5 sets of 20 lunges'),
(1, 6, 'FFTFTFF', 'Arms and Chest', 'Do 3 sets of bench, 2 sets of cleans, and 2 sets of 10 pull-ups'),
(1, 6, 'FFFFFFT', 'Cardio', 'Run for 45 minutes'),
(1, 7, 'FTFTFTF', 'Marathon Training', 'Run for 1 hour'),
(1, 7, 'FFTFTFF', 'Marathon Training', 'Run 5 miles for the first week for each day and 10 miles durring the second week')
;

-- Fixup Schema
-- ============

-- user_id sequence
select setval('app_user_user_id_seq', (select max(user_id) from app_user));

-- Foreign Key Constraints
ALTER TABLE client
ADD FOREIGN KEY(user_id)
REFERENCES app_user(user_id);

ALTER TABLE trainer
ADD FOREIGN KEY(user_id)
REFERENCES app_user(user_id);

ALTER TABLE client_list
ADD FOREIGN KEY(trainer_id) REFERENCES app_user(user_id),
ADD FOREIGN KEY(client_id)  REFERENCES app_user(user_id);

ALTER TABLE message
ADD FOREIGN KEY(sender_id)    REFERENCES app_user(user_id),
ADD FOREIGN KEY(recipient_id) REFERENCES app_user(user_id);


ALTER TABLE workout_plan
ADD FOREIGN KEY(trainer_id) REFERENCES app_user(user_id),
ADD FOREIGN KEY(client_id)  REFERENCES app_user(user_id);

-- Realistic values
-- ================

-- the password is 'password' for everyone
UPDATE app_user
SET
    username = UPPER(username),
    password = '327BtUzwOFiH7YN3BjySWA==',
    salt     = 'TCtA0l/RfWIfJkIRtEppHOp53FcciS4xSEJOu3z0J8kAOcKZFVQRu7ew4agRozh5Je6IL5Ruqv+gcSS4H1Mp6zPg0EOHQG16DQejzWNeZN3GIdi4E/368H2ze72papiIql8HmHhuDhQ6uS8VreE3xxo6ro19CenQp9ORnXEut3s='
;

-- the first 5 app_user are trainers, the rest are clients
UPDATE app_user
SET role = 'Trainer'
WHERE user_id <= 5;

UPDATE trainer SET is_public = random_boolean();

-- clients
INSERT INTO client (user_id)
SELECT user_id FROM app_user
WHERE user_id > 5;

COMMIT TRANSACTION;

